server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JeffersonRusso/Microservices-Spring-Boot
          search-paths: microservice-repo
          default-label: main